name: Start New site
favicon: null
layout_spectrum: 0.9712248460855335
typography_spectrum: 0.33116590860299766
title: Start New Site
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.42869613808579743
  lightness: 0.25910444115288556
  saturation: 0.3924244586378336
  rhythmicContrast: 0.49880532710812986
purpose: []
